apiVersion: v1
entries:
  oes:
  - apiVersion: v2
    appVersion: 3.10.9
    created: "2022-02-21T19:15:42.89104379+05:30"
    dependencies:
    - condition: global.installOpenLdap
      name: openldap
      repository: ""
      version: 1.2.3
    - condition: installSpinnaker
      name: spinnaker
      repository: ""
      version: 2.2.3
    - condition: global.minio.enabled
      name: minio
      repository: ""
      version: 8.0.9
    - condition: installRedis
      name: redis
      repository: ""
      version: 10.5.3
    - condition: enableCentralLogging
      name: elasticsearch
      repository: ""
      version: 7.5.0
    - condition: enableCentralLogging
      name: kibana
      repository: ""
      version: 7.5.0
    - condition: enableCentralLogging
      name: fluent-bit
      repository: ""
      version: 2.8.2
    - condition: spinnaker.enableCentralMonitoring
      name: prometheus
      repository: ""
      version: 11.16.2
    description: ISD 3.10.1 with log4j security fix and additional enhancements
    digest: cf85b2b12dae620e661d69ee10e734199312e82e134c08077d1c9a65d9a20971
    home: https://www.opsmx.com/
    icon: https://raw.githubusercontent.com/OpsMx/enterprise-spinnaker/master/img/opsmx.png
    keywords:
    - OpsMx
    - OES
    - Autopilot
    maintainers:
    - email: srinivas@opsmx.io
      name: ksrinimba
    name: oes
    urls:
    - oes-3.11.tgz
    version: "3.11"
generated: "2022-02-21T19:15:42.850555707+05:30"
