{{- if and (.Values.spinnaker.gitopsHalyard.mTLS.enabled) (.Values.spinnaker.gitopsHalyard.enabled) }}
apiVersion: v1
data:
  passphrase: Y2hhbmdlaXQ=
kind: Secret
metadata:
  name: passphrasesecret
{{- end }}
